# Site settings
title: SBR Strategic Pte Ltd
header-img: img/home-bg.jpg
email: vincent@sbrstrategic.com
copyright_name: SBR Strategic Pte Ltd
description: "SBR Strategic aims to bring success to ventures by providing early stage seed capital to promising startups. We seek companies focusing on ioT, commerce, home-automation,  and mobile services. SBR Strategic is based in Singapore."
baseurl: ""
url: "http://sbrstrategic.com"
twitter_username: techy_sg
github_username:  sbrstrategic
facebook_username:  sbrstrategic
email_username:  vincent@sbrstrategic.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-100434363-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
